site_name: PyCharm Documentation
site_url: 
theme:
  name: material
nav:
  - Home: "index.md"
  - Installation: "installation.md"
  - Configuration: "configuration.md"
  - Your First Program: "first_program.md"
  - Troubleshooting: "troubleshooting.md"
  - Glossary: "glossary.md"
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
